### ISSUE TITLE
Workflow's :config-auth parameter no longer exists

### ISSUE THREAD

**Issue by pjlegato** [clojusc/friend-oauth2-examples#7]
The example code refers to a :config-auth parameter (https://github.com/ddellacosta/friend-oauth2-examples/blob/master/src/friend_oauth2_examples/google_handler.clj#L57), but it seems that this no longer exists, according to https://github.com/ddellacosta/friend-oauth2/commit/bb366e481da515a500602abeeb4720c85e63bfaf .

**Comment by oubiwann** [comment]
There are some changes that have happened recently with friend-oauth2 and the examples -- primarily:
 * the friend-oauth2 repo is now maintained here: https://github.com/clojusc/friend-oauth2
 * the examples are now included in the friend-oauth2 repo itself, not in a separate repo

That being said, I believe this particular issue has been addressed? A `git grep ':config-auth'` doesn't turn anything up ...

For now, I will not port this issue over to the https://github.com/clojusc/friend-oauth2 repo, but if it turns out this is still an issue that needs to be addressed with the friend-oauth2 examples, I will do so :-)

**Comment by oubiwann** [comment]
I am going to close this issue, but if it still exists, we can create a new one here:
 * https://github.com/clojusc/friend-oauth2/issues
